version: '2.1'
volumes:
  resin-data:
  resin-screenshots:
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    restart: 'no'
    volumes:
      - 'resin-screenshots:/screenshots'
      # ====== Uncomment for easier local dev ======
      # - "./screenshots:/screenshots"
      # - "./integration-tests:/integration-tests"
    command: "wait-for-it.sh funes:3128 -- mocha --timeout 30000 --recursive /integration-tests"
    # command: ["sleep", "infinity"]
    depends_on:
      - funes
    # environment:
      # - TEST_URL=https://www.getmira.com
      # - DISABLE_PROXY=true
  funes:
    build:
      context: .
      dockerfile: Dockerfile.funes
    expose:
      - "3128"
    volumes:
      - 'resin-data:/data'
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "80:80"
    volumes:
      - 'resin-screenshots:/screenshots'
